services:
  server:
    build: .
    container_name: server
    ports:
      - "8080:8080"
    environment:
      POSTGRES_URL: postgres://kodeuser:kodepassword@postgres:5432/kodedb?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

  postgres:
    image: postgres:16.3-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: kodeuser
      POSTGRES_PASSWORD: kodepassword
      POSTGRES_DB: kodedb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U kodeuser -d kodedb" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  migrate:
    build: migrations
    environment:
      POSTGRES_URL: postgres://kodeuser:kodepassword@postgres:5432/kodedb?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
